#!/bin/sh
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/root/rv1106/lib
[ -f /etc/profile.d/RkEnv.sh ] && source /etc/profile.d/RkEnv.sh
case $1 in
	start)
#		sh /oem/usr/bin/RkLunch.sh
		;;
	stop)
#		sh /oem/usr/bin/RkLunch-stop.sh
		;;
	*)
		exit 1
		;;
esac
