#!/bin/sh
#
# Start the network....
#

# Debian ifupdown needs the /run/network lock directory
mkdir -p /run/network

case "$1" in
  start)
	printf "Starting network: "
	ifconfig eth0 hw ether 00:11:22:33:44:66
	/sbin/ifup -a
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	ifconfig eth0 up
	udhcpc -i eth0 &
	;;
  stop)
	printf "Stopping network: "
	/sbin/ifdown -a
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

